// Code generated by Slice Machine. DO NOT EDIT.
// Update these types by running `npx prismic-ts-codegen` after updating your custom types.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

// ─────────────────────────────────────────────────────────────────────────────
// Sport custom type
// ─────────────────────────────────────────────────────────────────────────────

export interface SportDocumentData {
  name: prismic.KeyTextField
  slug: prismic.KeyTextField
  icon: prismic.ImageField
  description: prismic.RichTextField
  active: prismic.BooleanField
}

export type SportDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<SportDocumentData>, 'sport', Lang>

// ─────────────────────────────────────────────────────────────────────────────
// Age Group custom type
// ─────────────────────────────────────────────────────────────────────────────

export interface AgeGroupDocumentData {
  label: prismic.KeyTextField
  sport: prismic.ContentRelationshipField<'sport'>
  description: prismic.KeyTextField
}

export type AgeGroupDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<AgeGroupDocumentData>, 'age_group', Lang>

// ─────────────────────────────────────────────────────────────────────────────
// Article custom type
// ─────────────────────────────────────────────────────────────────────────────

export type ArticleDocumentDataBodySlice =
  | RichTextSlice
  | VideoEmbedSlice
  | DrillDiagramSlice
  | CalloutBoxSlice
  | AdPlacementSlice
  | PrintableDownloadSlice

export interface ArticleDocumentData {
  title: prismic.KeyTextField
  sport: prismic.ContentRelationshipField<'sport'>
  age_group: prismic.ContentRelationshipField<'age_group'>
  tags: prismic.KeyTextField
  featured_image: prismic.ImageField
  summary: prismic.KeyTextField
  body: prismic.SliceZone<ArticleDocumentDataBodySlice>
  printable_pdf: prismic.LinkField
  published_date: prismic.DateField
  seo_title: prismic.KeyTextField
  seo_description: prismic.KeyTextField
}

export type ArticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<ArticleDocumentData>, 'article', Lang>

// ─────────────────────────────────────────────────────────────────────────────
// All document types
// ─────────────────────────────────────────────────────────────────────────────

export type AllDocumentTypes = SportDocument | AgeGroupDocument | ArticleDocument

// ─────────────────────────────────────────────────────────────────────────────
// Slice types
// ─────────────────────────────────────────────────────────────────────────────

// RichText
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<{ content: prismic.RichTextField }>,
  never
>
export type RichTextSliceVariation = RichTextSliceDefault
export type RichTextSlice = prismic.SharedSlice<'rich_text', RichTextSliceVariation>

// VideoEmbed
export type VideoEmbedSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<{ embed_url: prismic.KeyTextField; caption: prismic.KeyTextField }>,
  never
>
export type VideoEmbedSliceVariation = VideoEmbedSliceDefault
export type VideoEmbedSlice = prismic.SharedSlice<'video_embed', VideoEmbedSliceVariation>

// DrillDiagram
export type DrillDiagramSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<{ image: prismic.ImageField; description: prismic.RichTextField; drill_name: prismic.KeyTextField }>,
  never
>
export type DrillDiagramSliceVariation = DrillDiagramSliceDefault
export type DrillDiagramSlice = prismic.SharedSlice<'drill_diagram', DrillDiagramSliceVariation>

// CalloutBox
export type CalloutBoxSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<{
    type: prismic.SelectField<'tip' | 'warning' | 'info'>
    heading: prismic.KeyTextField
    content: prismic.RichTextField
  }>,
  never
>
export type CalloutBoxSliceVariation = CalloutBoxSliceDefault
export type CalloutBoxSlice = prismic.SharedSlice<'callout_box', CalloutBoxSliceVariation>

// AdPlacement
export type AdPlacementSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<{ ad_slot: prismic.SelectField<'leaderboard' | 'rectangle' | 'skyscraper'> }>,
  never
>
export type AdPlacementSliceVariation = AdPlacementSliceDefault
export type AdPlacementSlice = prismic.SharedSlice<'ad_placement', AdPlacementSliceVariation>

// PrintableDownload
export type PrintableDownloadSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<{
    title: prismic.KeyTextField
    description: prismic.KeyTextField
    file: prismic.LinkField
    button_label: prismic.KeyTextField
  }>,
  never
>
export type PrintableDownloadSliceVariation = PrintableDownloadSliceDefault
export type PrintableDownloadSlice = prismic.SharedSlice<'printable_download', PrintableDownloadSliceVariation>
